# @name article
POST http://localhost:3000/api/articles
Content-Type: application/json

{
  "title": "This is my first article draft",
  "content": "Test article content"
}

###

@articleId = {{article.response.body.$.id}}

PATCH http://localhost:3000/api/articles/{{articleId}}/publish

###
GET http://localhost:3000/api/articles

###
@articleId = {{article.response.body.$.id}}

POST http://localhost:3000/api/articles/{{articleId}}/comments
Content-Type: application/json

{
  "body": "Nice!"
}
