# @name article
POST http://localhost:3000/api/articles
Content-Type: application/json

{
  "title": "This is my first article",
  "content": "Test article content"
}

###
GET http://localhost:3000/api/articles?filter[publishedBetween]=2021-08-16T21:19:55.000Z&filter[publishedBetween]=2021-08-17T21:19:56.000Z&page=1

###
@articleId = {{article.response.body.$.id}}

POST http://localhost:3000/api/articles/{{articleId}}/comments
Content-Type: application/json

{
  "body": "Nice!"
}

###

@articleId = {{article.response.body.$.id}}

PATCH http://localhost:3000/api/articles/{{articleId}}/publish